# Build information from workflow inputs
luajava.branch=v4.0.2
redis.branch=8.2.2
version=1.1.0-SNAPSHOT
maven.group.id=org.infinispan
skip.publish=true

# Build metadata
github.workflow=Create Source Artifact
github.run.id=23187897513
github.run.number=62
github.actor=rigazilla
github.ref=refs/heads/main
github.sha=c6ed3a6389aab8448628792f3e31ee2f32564559
build.timestamp=2026-03-17T09:41:21Z
